# fly.toml app configuration file generated for wise-eyes on 2024-04-22T19:47:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wise-eyes'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8082
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 50
    soft_limit = 40

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
